vitessio/vitess-releaser

go/cmd/cmd.go, go/cmd/flags/flags.go, go/interactive/main_menu.go, go/interactive/pre_release/copy_branch_protection_rules.go, go/interactive/pre_release/create_github_milestones.go, go/interactive/pre_release/update_snapshot.go, go/interactive/release/close_milestone.go, go/interactive/ui/menu.go, go/releaser/ctx.go, go/releaser/github/issues.go, go/releaser/issue.go, go/releaser/milestone.go, go/releaser/pre_release/code_freeze.go, go/releaser/pre_release/copy_branch_protection_rules.go, go/releaser/pre_release/create_release_pr.go, go/releaser/pre_release/release_notes.go, go/releaser/pre_release/update_snapshot.go, go/releaser/prerequisite/summary.go, go/releaser/release/back_to_dev.go, go/releaser/release/release_notes_on_main.go, go/releaser/release/tag_release.go, go/releaser/slack/slack.go, go/releaser/steps/steps.go, go/releaser/vitess.go
This PR adds supports for RC releases. A new flag is added: `--rc=x` with `x` being the increment of the RC release you'd like to release.
=> Support RC releases

go/cmd/cmd.go, go/releaser/git/git.go, go/releaser/github/issues.go, go/releaser/github/milestone.go, go/releaser/github/pr.go, go/releaser/github/release.go, go/releaser/github/user.go, go/releaser/issue.go, go/releaser/milestone.go, go/releaser/pre_release/code_freeze.go, go/releaser/pre_release/create_release_pr.go, go/releaser/pre_release/release_notes.go, go/releaser/pre_release/vtop_update_golang.go, go/releaser/release/merge_pr.go, go/releaser/release/tag_release.go, go/releaser/release/vtop_create_release_pr.go, go/releaser/state.go, go/releaser/vitess.go
Moving all the `logs.Fatal` to `logs.Panic` in order to ease debugging if something goes wrong during a release
=> Replace all logs.Fatal by logs.Panic

go/releaser/github/branch.go
Fix an issue seen during RC-1, the fields were not sent to the API although they are mandatory, leading to a panic
=> Fix branch protection rules copy

go/interactive/general_prereq.go, go/releaser/issue.go
There was an issue where the status (done/not done) of the general prerequisite step was not saved properly on the issue. Now, in the UI when marking the item as done/not done, all the items of the list are checked or unchecked.
=> Fix how the status of the general prerequisite is handled

go/releaser/github/pr.go, go/releaser/issue.go, go/releaser/prerequisite/check_and_add.go
There was an issue when doing RC-1 we were overriding all previous listed backports/prs in the issue. Also the branch we used to list important PRs was wrong. Also a minor issue with how we parsed the date in the issue.
=> Fix how we list backports

go/interactive/code_freeze/create_new_labels.go, go/interactive/main_menu.go, go/releaser/code_freeze/create_new_labels.go, go/releaser/issue.go, go/releaser/steps/steps.go
Until now the creation of the release blocker label was often forgotten. Now it is done automatically by the tool at the same time as creating the two backport to labels.
=> Automate the creation of the release-blocker label

go/releaser/release/docker.go
While working on https://github.com/vitessio/vitess/pull/16196 I realized that we do not actually used the two workflows (`docker_build_old_base.yml` and `docker_build_old_lite.yml`) which I linked to in a previous PR #99. I am reverting that change to keep using the original workflow names.
=> Fix workflow links for < v20 release

CONTRIBUTING.md, Makefile, README.md, go/cmd/cmd.go, go/interactive/ui/dialogue_done.go, go/interactive/ui/menu.go, go/interactive/ui/utils.go, go/releaser/issue.go
1. Show version which includes the last git commit
2. Initial Makefile
3. Minor text and style mods
4. Initial Contribution doc for local install and development tips/tricks
=> Add version flag, contribution doc, small UI enhancements

go/releaser/code_freeze/milestone.go
During RC-1's code freeze, we create the new release branch and a new milestone (i.e. `v21.0.0`), however we were not moving the PRs from the previous milestone (`v20.0.0`), into the new one (`v21.0.0`). Meaning that we had PRs on the `main` branch that were still assigned to the `v20.0.0` milestone although these specific PRs were never going to make it to the `v20.0.0` release (maybe they would have thanks to backport, but that does not matter).
Eventually during the release step of GA, we migrate all the opened PRs from the `v20.0.0` milestone to the new `v21.0.0` milestone, but that happens too late already.
This PR fixes this issue by migrating all opened PRs from the current to the next milestone during RC-1's code freeze.
=> Move PRs to newer milestone when doing RC-1

go/interactive/release/vtop_manual_update.go, go/releaser/release/vtop_manual_update.go, go/releaser/release/website_docs.go, go/releaser/vitess.go
This PR modifies the text of the manual steps (website docs update and vtop tests update) with something that is more clear and easier to understand. The actual content that has to be written was inserted in the text, so no need to guess what has to be updated.
**Vtop when doing v20.0.0-rc1 release:**
**Website docs when doing v20.0.0-rc1 release:**
=> Enhance the description of the manual steps (website docs and vtop)

go/releaser/pre_release/vtop_update_compatibility_table.go
=> Fix typo in the compatibility table step

go/releaser/blog_post.go, go/releaser/git/git.go, go/releaser/issue.go, go/releaser/prerequisite/summary.go, go/releaser/release/java.go
I did a GA release on my own fork, and came up with these minor improvements:
- Better explanations around the blog post
- Fix an issue when reading the link of the release pull request
- Fix a tiny typo in java.go
=> Enhance the the flow for GA releases

go/releaser/release/docker.go
After https://github.com/vitessio/vitess/pull/16339 the link to check the status of the docker build changed, this PR update the docker step for `>= v21` releases.
=> Use newer links to check the docker images

go/interactive/menu_item_constructors.go, go/releaser/release/docker.go
This PR changes the "Check Docker" step to add a DockerHub link enabling the release lead to check whether the vitess-operator Docker Image has been correctly built.
=> Ensure vitess-operator image is correctly built

go/interactive/pre_release/vtop_update_golang.go, go/releaser/pre_release/vtop_update_golang.go
The `Update Go version in vitess-operator` step (pre-release) used to only update the Golang version used in vtop if vtop was behind by at least 1 golang major version. Since we recently changed vitess' go mod, we must be using the proper Golang version in vtop's test and docker images at all time to ensure that the tests are passing. This PR changes the mechanism and always make sure that both repositories are on the exact same Golang version, if not a PR is automatically created to update the Golang version of vtop.
In this PR I am also adding some code to change the Golang version in the buildkite pipeline, which was missed before.
**Testing:**
https://github.com/frouioui/vitess/issues/364 is my testing release issue, and when running the step I end up with a new PR to update the Go …
=> Prevent Golang mismatch between vitess and vtop

go/cmd/cmd.go, go/releaser/code_freeze/code_freeze.go, go/releaser/git/git.go, go/releaser/github/branch.go, go/releaser/github/issues.go, go/releaser/github/milestone.go, go/releaser/github/pr.go, go/releaser/github/release.go, go/releaser/github/user.go, go/releaser/issue.go, go/releaser/milestone.go, go/releaser/pre_release/create_release_pr.go, go/releaser/pre_release/release_notes.go, go/releaser/pre_release/vtop_bump_version_on_main.go, go/releaser/pre_release/vtop_update_golang.go, go/releaser/release/java.go, go/releaser/release/merge_pr.go, go/releaser/release/tag_release.go, go/releaser/release/vtop_create_release_pr.go, go/releaser/state.go, go/releaser/utils/utils.go, go/releaser/vitess.go, go/vitess-releaser.go
We used to panic on various errors in the releaser. Some stack traces are very large and maybe contain control characters, not allowing us to scroll back to the top of the error stack and needing an `stty sane` to restore the terminal.
This PR replaces panics by printing the error and the debug stack and exiting. It also handles inadvertent panics via a recover and logging.
=> Improve error logging

README.md
Quick follow up of https://github.com/vitessio/vitess-releaser/pull/112 which describes how one can author PRs using a different GH account.
=> Update README with new authentication flow

go/releaser/code_freeze/copy_branch_protection_rules.go, go/releaser/code_freeze/create_new_labels.go
This PR is a follow up of when we removed the RC branch (i.e. `release-20.0-rc`), we still had some left over sub-steps.
Part of https://github.com/vitessio/vitess-releaser/issues/114
=> Remove duplicated (base and real release branch) sub-steps

go/interactive/code_freeze/vtop_bump_version_on_main.go, go/interactive/code_freeze/vtop_create_branch.go, go/interactive/main_menu.go, go/interactive/menu_item_constructors.go, go/releaser/code_freeze/vtop_bump_version_on_main.go, go/releaser/code_freeze/vtop_create_branch.go, go/releaser/code_freeze/vtop_update_compatibility_table.go, go/releaser/issue.go, go/releaser/release/vtop_create_release_pr.go, go/releaser/steps/steps.go
This PR moves three vtop related steps from pre-release to code freeze. They had nothing to do in the pre-release and are artefacts from the previous release process.
Part of https://github.com/vitessio/vitess-releaser/issues/114
=> Move some vtop steps to code freeze

go.mod, go.sum, go/cmd/cmd.go, main.go
This PR will allow us to check the version of the tool used by the user dynamically and ensure the user is running the latest version of the tool at all time.
=> Check the version of the tool at start time

Makefile, go/cmd/cmd.go, go/interactive/main_menu.go, go/interactive/menu_item_constructors.go, go/releaser/issue.go, go/releaser/post_release/protection_rules.go, go/releaser/pre_release/cobra_docs.go, go/releaser/release/artifacts.go, go/releaser/release/docker.go, go/releaser/state.go, go/releaser/steps/steps.go
See https://github.com/vitessio/vitess/issues/16795#todos
=> Add vitess releaser items specified in https://github.com/vitessio/vitess/issues/16795#todos

go/interactive/main_menu.go, go/interactive/release/vtop_back_to_dev.go, go/interactive/release/vtop_create_release_pr.go, go/interactive/release/vtop_merge_release_pr.go, go/interactive/release/vtop_tag_release.go, go/releaser/issue.go, go/releaser/release/vtop_back_to_dev.go, go/releaser/release/vtop_create_release_pr.go, go/releaser/release/vtop_manual_update.go, go/releaser/release/vtop_merge_pr.go, go/releaser/release/vtop_tag_release.go, go/releaser/steps/steps.go
This PR is long due, it finally changes the release process of vitess-operator by making sure the Release PR is created first. It breaks down the current `Create vitess-operator release PR` step into multiple steps:
- `Create vitess-operator Release PR`
- `Merge the vitess-operator Release PR` **(new step)**
- `Tag the vitess-operator release` **(new step)**
- `Back To Dev Mode vitess-operator` **(new step)**
- `Manual update of vitess-operator tests`
The first step shown above is now only responsible for creating the Release PR (instead of doing everything that's automated), and the last step was moved from the early stage of the `Release` phase to the very end of the phase.
As we must create the vtop Release PR once the Vitess release is out (they're linked to each other, vtop uses the …
=> Improve vtop release process by creating the Release PR first

go/cmd/cmd.go
Bumping the main branch to version 1.0.5 after the release of v1.0.4.
=> Bump to version 1.0.5

go/releaser/release/artifacts.go
Small update to the "check release artifacts" step, it was cumbersome to find the related workflow that needed to be checked, adding a link will now make the step easier to follow.
=> Add a link to the `create_release.yml` workflow in the release artifacts step

go/interactive/release/java.go, go/releaser/issue.go, go/releaser/release/java.go
This PR updates the Java release step, we will now run it for both RCs and GAs releases - instead of just GAs. This PR also omit the `-DskipTests` mvn flag for >= v22.0 releases.
=> Update Java command and run it for both RCs and GAs

go.mod, go/interactive/ui/ui.go, go/releaser/code_freeze/code_freeze.go, go/releaser/code_freeze/update_snapshot.go, go/releaser/code_freeze/vtop_bump_version_on_main.go, go/releaser/github/pr.go, go/releaser/pre_release/create_release_pr.go, go/releaser/pre_release/vtop_update_golang.go, go/releaser/release/back_to_dev.go, go/releaser/release/copy_release_notes.go, go/releaser/release/docker.go, go/releaser/release/vtop_back_to_dev.go, go/releaser/release/vtop_create_release_pr.go
This PR fixes https://github.com/vitessio/vitess-releaser/issues/130 by implementing:
- Helper text (current version, repository, release date) is now visible in more places, even outside of the main menu.
- Go has been upgraded to `go1.24.1`
- The link to see the docker build workflow for `>= v21` has been fixed
- Every Pull Request created by the tool now reference its release issue in the PR's description (e.g. https://github.com/frouioui/vitess/pull/376)
=> Minor improvements ahead of the `v22.0.0` release

go/releaser/code_freeze/copy_branch_protection_rules.go
Fixes a small UI bug where the amount of steps was incorrect.
=> Correctly set the number of steps in branch protection rules copy
